name: Unitc Test

on:
  workflow_dispatch:
  push:
    branches-ignore: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run unitc tests
        run: make test
